// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://objzhrsmmjesndopagba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ianpocnNtbWplc25kb3BhZ2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTE4NTQsImV4cCI6MjA2MDEyNzg1NH0.GDZJfeGiopVj9g0bUPXbp3PSJE_XOWiB5PTKgS7EI2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);