// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwljcyqphvoblvdircur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3bGpjeXFwaHZvYmx2ZGlyY3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTM4NjgsImV4cCI6MjA2MTkyOTg2OH0.R3R0pkbQZAW--yx7uEI_qFxZKbfjit_y3c_0m6LwiI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);